# Generated by Django 3.2.8 on 2021-10-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('contato', models.CharField(max_length=25)),
                ('escolaridade', models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Ensino Superior', 'Ensino Superior')], max_length=30)),
                ('sobre', models.TextField(max_length=1000)),
                ('tipo', models.TextField(max_length=50)),
            ],
        ),
    ]
